// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF2cql5HvGofb7KBO8J7UMZuL_jXaRBo8',
    appId: '1:258043326131:web:7537ce5a7b6e1b931c8ac6',
    messagingSenderId: '258043326131',
    projectId: 'final-project-auth-b222c',
    authDomain: 'final-project-auth-b222c.firebaseapp.com',
    storageBucket: 'final-project-auth-b222c.firebasestorage.app',
    measurementId: 'G-BBQ6E7GKKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6hbjW71GthuqPaugxpIegYKE8VVAN-3s',
    appId: '1:258043326131:android:a158458cbfe85c011c8ac6',
    messagingSenderId: '258043326131',
    projectId: 'final-project-auth-b222c',
    storageBucket: 'final-project-auth-b222c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcCJTfgYiMoJacclLE_BKj-LfoXWROdJs',
    appId: '1:258043326131:ios:12b46476c24449071c8ac6',
    messagingSenderId: '258043326131',
    projectId: 'final-project-auth-b222c',
    storageBucket: 'final-project-auth-b222c.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF2cql5HvGofb7KBO8J7UMZuL_jXaRBo8',
    appId: '1:258043326131:web:d0973bb0852772271c8ac6',
    messagingSenderId: '258043326131',
    projectId: 'final-project-auth-b222c',
    authDomain: 'final-project-auth-b222c.firebaseapp.com',
    storageBucket: 'final-project-auth-b222c.firebasestorage.app',
    measurementId: 'G-NRZCH6L5QW',
  );
}
